version: 2.1
aliases:
  - &restore-cache
    restore_cache:
        keys:
        - v1-dependencies-
        - v1-dependencies-
  - &install-deps
    run:
        name: Install dependencies
        command: npm i

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    environment:
      DOCKER_IMAGE: ichhoa129/test
      DOCKER_TAG: latest
    working_directory: ~/express-example
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker
      - *restore-cache
      - run: npm cache clear --force
      - run:
          name: Update NPM version
          command: 'sudo npm install -g npm@latest'
      - *install-deps
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
       
  deploy:
    docker:
      - image: circleci/node:14
    working_directory: ~/express-example
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5c:b4:f2:fa:8d:c0:ae:ea:6e:29:c0:9c:7d:08:0d:72"
      - run: 
          name: Deploy via ssh
          command: |
              echo Starting to deploy server
              ssh -oStrictHostKeyChecking=no -v $SSH_USER@$SSH_HOST 'cd ~/express-example/ && git checkout test_circleci && git pull && echo $PATH && npm i && pm2 start app.json'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy